name: Check

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        name: Check
        steps:
            - uses: actions/checkout@v2
            - name: cargo check
              run: cargo check
