name: Tests

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        name: Test
        steps:
            - uses: actions/checkout@v2
            - name: cargo test
              run: cargo test
